version: '3'
services:
    python:
        container_name: web
        # image: python:latest
        build: ./web
        working_dir: /web
        # expose:
        #     - "8003"
        ports:
            - "8003:8003"
        volumes:
            - ./web:/web
        command: uwsgi --ini uwsgi.ini

    nginx:
        container_name: nginx
        # build: ./nginx
        image: nginx:latest
        ports:
            # - "80:80"
            - "443:443"
        volumes:
            - ./web:/web
            - ./nginx/log:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/nginx/ssl
            # - ./my_htpasswd:/my_htpasswd